### ISSUE TITLE
Strict mode with Chrome

### ISSUE THREAD

**Issue by ghost** [leotiger/grav-plugin-backup-manager#1]
Great job, man!

No problem with Firefox.
Using Google Chrome you get this error:

`backup-manager.js: 8 Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

At the beginning of the file you need to add `"use strict";`
Now it seems that everything works!

**Comment by leotiger** [comment]
Version 0.1.1 fixes this with some other minor fixes and improvements.

Thanks @iusvar for reporting.

u
