### ISSUE TITLE
Broken with grav 1.1.16

### ISSUE THREAD

**Issue by muflone** [leotiger/grav-plugin-backup-manager#6]
After installation, opening the backup manager page the following exception is raised:

An exception has been thrown during the rendering of a template ("Undefined property: Grav\Plugin\BackupManager\BackupManager::$admin").

The highlighted line is the number 5 of backup-manager.html.twig
{% set storestatus = backupmanager.storeStatus() %}

**Comment by leotiger** [comment]
Hi @muflone 

I did a clean install on a grav 1.1.16 website and I cannot confirm this problem. I even uninstalled, deleted the backup-manager.yaml from user/config/plugin and installed again, without problems as well.

How did you install? Via cli?

**Comment by muflone** [comment]
I've installed the plugin from the grav plugins repository.

I'll test it again ASAP

**Comment by muflone** [comment]
After disabling all plugins except admin, the issue persists.
What can I look to trace the source of the issue?

**Comment by leotiger** [comment]
Ok, I had a look at the code. You're right. There's a bug. You can "fix" this yourself saving the configuration for Backup Manager once via the admin plugin. Once saved you should not receive any errors if you define a positive value in GB for storage.

I will update the plugin tomorrow to fix this.

Thanks.
u

**Comment by muflone** [comment]
oh yes, confirmed.
after saving the configuration the issue is gone.
thank you

**Comment by leotiger** [comment]
Fixed in  v0.1.4
